const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={targets:[],jobs:[],targetId:null,jobId:null,file:'params.csv',logTimer:null};
const api=async(path,options={})=>{const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data};
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2400)};
const formObject=form=>Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,v]));
const cleanOptions=form=>{const values=formObject(form);$$('input[type=checkbox]',form).forEach(input=>values[input.name]=input.checked);for(const [key,value] of Object.entries(values))if(value==='')delete values[key];return values};
const formatTime=value=>value?new Date(value).toLocaleString([], {month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const formatBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const selectedTarget=()=>state.targets.find(t=>t.id===state.targetId);
const selectedJob=()=>state.jobs.find(j=>j.id===state.jobId);

async function refresh(){const data=await api('/api/state');state.targets=data.targets;state.jobs=data.jobs;if(!state.targetId&&state.targets.length)state.targetId=state.targets[0].id;if(state.targetId&&!state.targets.some(t=>t.id===state.targetId))state.targetId=state.targets[0]?.id||null;render();}
function render(){renderTargets();renderTarget();renderJobs();renderInspector();}
function renderTargets(){const search=$('#target-search').value.toLowerCase();const targets=state.targets.filter(t=>`${t.name} ${t.identifier_value}`.toLowerCase().includes(search));$('#target-count').textContent=state.targets.length;$('#target-list').innerHTML=targets.map(t=>`<button class="target-item ${t.id===state.targetId?'active':''}" data-target="${t.id}"><i class="target-state ${t.latest_status||''}"></i><span><strong>${escapeHtml(t.name)}</strong><small>${t.identifier_type.toUpperCase()} ${escapeHtml(t.identifier_value)}</small></span><em>${t.job_count}</em></button>`).join('')||'<p class="empty-small">Add the first target.</p>';$$('[data-target]').forEach(b=>b.onclick=()=>selectTarget(+b.dataset.target));}
async function selectTarget(id){state.targetId=id;state.jobId=state.jobs.find(j=>j.target_id===id)?.id||null;render();await Promise.all([drawSeries(),loadFile(),loadArtifacts()]);}
function renderTarget(){const t=selectedTarget();$('#target-title').textContent=t?.name||'Start with a target';$('#target-identifier').textContent=t?`${t.identifier_type.toUpperCase()} ${t.identifier_value}`:'No target selected';$('#target-path').textContent=t?.data_dir||'—';$('#prepare-top').disabled=!t;$('#delete-target').disabled=!t;}
function renderJobs(){const jobs=state.jobs.filter(j=>j.target_id===state.targetId);$('#history-summary').textContent=jobs.length?`${jobs.length} recorded job${jobs.length===1?'':'s'}`:'No jobs';$('#job-history').innerHTML=jobs.map(j=>`<button class="job-row" data-job="${j.id}"><i class="dot ${j.status}"></i><strong>${j.kind.replaceAll('-',' ')}</strong><span>${j.status}</span><time>${formatTime(j.created_at)}</time><span>#${j.id}</span></button>`).join('')||'<p class="empty-message">No work has run for this target. Start with preparation.</p>';$$('[data-job]').forEach(b=>b.onclick=()=>{state.jobId=+b.dataset.job;renderInspector();pollLog()});}
function renderInspector(){const j=selectedJob();$('#job-title').textContent=j?j.kind.replaceAll('-',' '):'No active job';const status=$('#job-status');status.textContent=j?.status||'idle';status.className=`status ${j?.status||'idle'}`;$('#job-created').textContent=formatTime(j?.created_at);$('#job-pid').textContent=j?.pid||'—';$('#job-exit').textContent=j?.returncode??'—';$('#job-command').textContent=j?.command?.join(' ')||'Select a job to inspect its command.';$('#job-elapsed').textContent=j?elapsed(j):'—';$('#cancel-job').disabled=!j||!['queued','running'].includes(j.status);}
function elapsed(j){const start=j.started_at||j.created_at;if(!start)return'—';const end=j.finished_at?new Date(j.finished_at):new Date();const seconds=Math.max(0,Math.floor((end-new Date(start))/1000));return`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
async function pollLog(){clearTimeout(state.logTimer);const j=selectedJob();if(!j)return;try{const data=await api(`/api/log?job_id=${j.id}`);$('#job-log').textContent=data.content||'Waiting for output…';$('#job-log').scrollTop=$('#job-log').scrollHeight;if(['queued','running'].includes(data.status)){state.logTimer=setTimeout(async()=>{await refresh();pollLog()},1600)}}catch(e){$('#job-log').textContent=e.message}}
async function drawSeries(){const group=$('#lightcurve .points'),empty=$('#plot-empty');group.innerHTML='';const t=selectedTarget();if(!t){empty.hidden=false;return}const data=await api(`/api/series?target_id=${t.id}`);if(!data.time.length){empty.hidden=false;return}empty.hidden=true;const xs=data.time,ys=data.flux,minX=Math.min(...xs),maxX=Math.max(...xs),sorted=[...ys].sort((a,b)=>a-b),lo=sorted[Math.floor(sorted.length*.01)],hi=sorted[Math.floor(sorted.length*.99)]||lo+1;group.innerHTML=xs.map((x,i)=>`<circle cx="${((x-minX)/(maxX-minX||1))*1200}" cy="${185-((ys[i]-lo)/(hi-lo||1))*160}" r="1.7"/>`).join('');$('#axis-start').textContent=minX.toFixed(3);$('#axis-end').textContent=maxX.toFixed(3)}
async function loadFile(){const t=selectedTarget();if(!t){$('#file-editor').value='';return}try{const data=await api(`/api/file?target_id=${t.id}&name=${encodeURIComponent(state.file)}`);$('#file-editor').value=data.content;$('#editor-state').textContent=data.exists?`${state.file} loaded`:`${state.file} has not been generated`;updateLines()}catch(e){$('#editor-state').textContent=e.message}}
function updateLines(){const count=$('#file-editor').value.split('\n').length;$('#editor-lines').textContent=Array.from({length:count},(_,i)=>i+1).join('\n')}
async function loadArtifacts(){const t=selectedTarget();if(!t)return;const items=await api(`/api/artifacts?target_id=${t.id}`);const figures=items.filter(x=>x.preview).slice(0,8);$('#figure-gallery').innerHTML=figures.map(x=>`<figure class="figure-card"><img loading="lazy" src="/api/artifact?target_id=${t.id}&path=${encodeURIComponent(x.path)}" alt="${escapeHtml(x.path)}"><figcaption>${escapeHtml(x.path)}</figcaption></figure>`).join('');$('#artifact-list').innerHTML=items.map(x=>`<div class="artifact-row"><span>${escapeHtml(x.path)}</span><span>${formatBytes(x.size)}</span><span>${formatTime(x.modified)}</span></div>`).join('')||'<p class="empty-message">Artifacts appear here after preparation and inference.</p>'}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showTab(name){$$('.workflow-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));if(name==='validate')loadFile();if(name==='results')loadArtifacts()}

$$('.workflow-tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#target-search').oninput=renderTargets;$('#new-target-button').onclick=()=>$('#target-dialog').showModal();
$('#target-form').onsubmit=async event=>{event.preventDefault();try{const target=await api('/api/targets',{method:'POST',body:JSON.stringify(formObject(event.target))});state.targetId=target.id;event.target.reset();$('#target-dialog').close();toast('Target added');await refresh();await selectTarget(target.id)}catch(e){toast(e.message)}};
$('#prepare-top').onclick=()=>showTab('prepare');
$('#prepare-form').oninput=()=>{const v=cleanOptions($('#prepare-form'));$('#prepare-command').textContent=`allesfitter prepare --${selectedTarget()?.identifier_type||'target'} ${selectedTarget()?.identifier_value||'…'} --${v.window_type||'sector'} ${v.window_value||'-1'} …`};
$('#prepare-form').onsubmit=async event=>{event.preventDefault();if(!state.targetId)return toast('Add or select a target first');try{const job=await api('/api/jobs',{method:'POST',body:JSON.stringify({target_id:state.targetId,kind:'prepare',options:cleanOptions(event.target)})});state.jobId=job.id;toast('Preparation started');showTab('run');await refresh();pollLog()}catch(e){toast(e.message)}};
$('#run-form').onsubmit=async event=>{event.preventDefault();if(!state.targetId)return toast('Select a target first');const options=cleanOptions(event.target),kind=options.kind;delete options.kind;try{const job=await api('/api/jobs',{method:'POST',body:JSON.stringify({target_id:state.targetId,kind,options})});state.jobId=job.id;toast(`${kind.replaceAll('-',' ')} started`);await refresh();pollLog()}catch(e){toast(e.message)}};
$$('.editor-tabs button').forEach(b=>b.onclick=()=>{$$('.editor-tabs button').forEach(x=>x.classList.toggle('active',x===b));state.file=b.dataset.file;loadFile()});
$('#file-editor').oninput=updateLines;$('#file-editor').onscroll=()=>{$('#editor-lines').scrollTop=$('#file-editor').scrollTop};
$('#save-file').onclick=async()=>{if(!state.targetId)return toast('Select a target first');try{await api('/api/file',{method:'PUT',body:JSON.stringify({target_id:state.targetId,name:state.file,content:$('#file-editor').value})});$('#editor-state').textContent=`${state.file} saved`;toast('Changes saved')}catch(e){toast(e.message)}};
$('#refresh-artifacts').onclick=loadArtifacts;$('#delete-target').onclick=async()=>{const t=selectedTarget();if(!t||!confirm(`Delete target ${t.name}? This cannot be undone.`))return;try{await api(`/api/targets/${t.id}`,{method:'DELETE'});state.targetId=null;toast('Target deleted');await refresh()}catch(e){toast(e.message)}};$('#cancel-job').onclick=async()=>{const j=selectedJob();if(!j)return;try{await api(`/api/jobs/${j.id}/cancel`,{method:'POST',body:'{}'});toast('Job cancelled');await refresh()}catch(e){toast(e.message)}};
$('#copy-log').onclick=()=>navigator.clipboard.writeText($('#job-log').textContent).then(()=>toast('Log copied'));
setInterval(()=>{const j=selectedJob();if(j)$('#job-elapsed').textContent=elapsed(j)},1000);
refresh().then(()=>{if(state.targetId)selectTarget(state.targetId)}).catch(e=>toast(e.message));
