"""Serialize a :class:`~allesfitter.webgui.models.FitConfig` into an allesfitter
datadir: ``settings.csv`` + ``params.csv`` + ``run.py`` + ``meta.yaml``.

This is the GUI ↔ engine decoupling seam (muscat-db's ``_write_fit_inputs``
pattern): the *same* writer feeds a real run and the dry-run validator. It
targets the engine's exact vocabulary — the authoritative allowed keys live in
``allesfitter/basement.py`` (``valid_settings_keys`` + per-instrument prefixes),
and the emitted parameter names follow ``get_rr_key`` / ``get_ldc_key`` (radius
ratio and limb darkening keyed by *bandpass*) and the ``baseline_*`` /
``error_*`` per-instrument keys.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

import yaml

from allesfitter.webgui import instruments as _inst
from allesfitter.webgui import models as m

# run.py generated into every run dir. Reads ALLESFIT_SAMPLER so the same file
# works standalone, via the web launcher, and via scripts/run_allesfitter_grid.py.
RUN_PY_TEMPLATE = '''#!/usr/bin/env python
"""Auto-generated by allesfitter.webgui — runs allesfitter on THIS datadir.
Default sampler is MCMC; set ALLESFIT_SAMPLER=ns for Nested Sampling (log(Z))."""
import os

os.environ["OMP_NUM_THREADS"] = "1"
import allesfitter

DATADIR = os.path.dirname(os.path.abspath(__file__))
SAMPLER = os.environ.get("ALLESFIT_SAMPLER", "mcmc").lower()

allesfitter.show_initial_guess(DATADIR)
if SAMPLER == "ns":
    with allesfitter.log_run("ns_fit", DATADIR):
        allesfitter.ns_fit(DATADIR, overwrite=False)
    allesfitter.ns_output(DATADIR, overwrite=True)
else:
    allesfitter.optimize(DATADIR, method="differential_evolution", refine=True)
    with allesfitter.log_run("mcmc_fit", DATADIR):
        allesfitter.mcmc_fit(DATADIR, append=True)
    allesfitter.mcmc_output(DATADIR, overwrite=True)
'''

# params.csv column header (commented, matching the examples).
_PARAMS_HEADER = "#name,value,fit,bounds,label,unit,coupled_with"


def _num(value: object) -> str:
    """Format a scalar for CSV (``str`` round-trips floats exactly in py3)."""
    if isinstance(value, bool):
        return "True" if value else "False"
    return str(value)


def _bool(value: bool) -> str:
    return "True" if value else "False"


def _param_row(name: str, p: m.Prior) -> str:
    if p.fit and not p.bounds:
        raise ValueError(f"parameter '{name}' is fitted (fit=1) but has empty bounds")
    return ",".join(
        [name, _num(p.value), "1" if p.fit else "0", p.bounds, p.label, p.unit, p.coupled_with]
    )


# --- settings.csv ----------------------------------------------------------
def build_settings(cfg: m.FitConfig) -> str:
    """Return the full text of ``settings.csv`` for *cfg*."""
    insts = cfg.instruments
    comp_names = [c.name for c in cfg.companions]
    lines: list[str] = ["#name,value"]

    def sec(title: str) -> None:
        lines.append("#" + "=" * 76)
        lines.append("# " + title)
        lines.append("#" + "=" * 76)

    def kv(key: str, value: object) -> None:
        lines.append(f"{key},{_num(value)}")

    sec("General settings")
    kv("companions_phot", " ".join(comp_names))
    kv("companions_rv", "")
    kv("inst_phot", " ".join(i.label for i in insts))
    kv("inst_rv", "")
    kv("bandpass", " ".join(i.band for i in insts))
    if cfg.chromatic is not None:
        kv("chromatic", _bool(cfg.chromatic))
    kv("time_format", cfg.time_format)

    sec("Fit performance settings")
    kv("multiprocess", _bool(cfg.multiprocess))
    kv("multiprocess_cores", cfg.multiprocess_cores)
    kv("fast_fit", _bool(cfg.fast_fit))
    kv("fast_fit_width", cfg.fast_fit_width)
    kv("secondary_eclipse", "False")
    kv("phase_curve", "False")
    kv("shift_epoch", _bool(cfg.shift_epoch))
    if cfg.shift_epoch:
        for name in comp_names:
            kv(f"inst_for_{name}_epoch", "all")

    sec("MCMC settings")
    for key, value in cfg.mcmc.items():
        kv(key, value)

    sec("Nested Sampling settings")
    for key, value in cfg.ns.items():
        kv(key, value)

    sec("Limb darkening law per instrument")
    for i in insts:
        kv(f"host_ld_law_{i.label}", i.ld_law)

    sec("Baseline model per instrument")
    for i in insts:
        kv(f"baseline_flux_{i.label}", i.baseline)
        if i.baseline in _inst.MULTI_BASELINES:
            cols = list(i.baseline_cols)
            if "bias" not in cols:
                cols.append("bias")
            kv(f"baseline_flux_{i.label}_cols", " ".join(cols))
    if cfg.share_groups:
        kv("baseline_share_flux", " ".join(":".join(g) for g in cfg.share_groups))

    sec("Error scaling per instrument")
    for i in insts:
        kv(f"error_flux_{i.label}", i.error)

    sec("Priors / physics")
    kv("use_host_density_prior", _bool(cfg.use_host_density_prior))
    kv("fit_ttvs", _bool(cfg.fit_ttvs))

    sec("Exposure time + stellar grid per instrument")
    for i in insts:
        if i.t_exp is not None:
            kv(f"t_exp_{i.label}", i.t_exp)
    for i in insts:
        kv(f"host_grid_{i.label}", i.grid)
        for name in comp_names:
            kv(f"{name}_grid_{i.label}", i.grid)

    return "\n".join(lines) + "\n"


# --- params.csv ------------------------------------------------------------
def _rr_rows(cfg: m.FitConfig, comp: m.CompanionSpec) -> list[str]:
    """Radius-ratio rows, keyed by bandpass unless explicitly achromatic.

    Mirrors ``Basement.get_rr_key``: with a bandpass row present (always, here),
    rr is keyed by band as ``<name>_rr_<band>`` — one per unique band — unless
    the user forced ``chromatic=False``, which collapses to a single ``<name>_rr``.
    """
    if cfg.chromatic is False:
        return [_param_row(f"{comp.name}_rr", comp.rr)]
    rows: list[str] = []
    for band in cfg.unique_bands():
        p = m.Prior(
            comp.rr.value,
            comp.rr.fit,
            comp.rr.bounds,
            label=rf"$R_{{{comp.name}; {band}}} / R_\star$",
            unit=comp.rr.unit,
            coupled_with=comp.rr.coupled_with,
        )
        rows.append(_param_row(f"{comp.name}_rr_{band}", p))
    return rows


def _baseline_param_rows(cfg: m.FitConfig, inst: m.InstrumentSpec) -> list[str]:
    """Sampled baseline parameters for *inst* by baseline model.

    GP hyperparameters are emitted only for a share-group *leader* (or an
    independent GP instrument); followers inherit the leader's GP, matching the
    engine's ``baseline_share_flux`` propagation.
    """
    b = inst.baseline
    label = inst.label
    if b == "sample_offset":
        off = inst.baseline_offset or m.default_offset()
        return [_param_row(f"baseline_offset_flux_{label}", off)]
    if b == "sample_linear":
        off = inst.baseline_offset or m.default_offset()
        slope = inst.baseline_slope or m.default_slope()
        return [
            _param_row(f"baseline_offset_flux_{label}", off),
            _param_row(f"baseline_slope_flux_{label}", slope),
        ]
    if b == "sample_GP_Matern32":
        if label in cfg.follower_labels():
            return []
        lnsigma = inst.gp_lnsigma or m.default_gp_lnsigma()
        lnrho = inst.gp_lnrho or m.default_gp_lnrho()
        return [
            _param_row(f"baseline_gp_matern32_lnsigma_flux_{label}", lnsigma),
            _param_row(f"baseline_gp_matern32_lnrho_flux_{label}", lnrho),
        ]
    if (
        b in ("none", "hybrid_offset", "hybrid_spline", "hybrid_spline_s")
        or b.startswith("hybrid_poly_")
        or b == "hybrid_linear_multi"
    ):
        # No sampled parameters (hybrid_* solved/marginalised at each likelihood).
        return []
    raise NotImplementedError(
        f"config_writer cannot yet emit params for baseline '{b}' (instrument '{label}'). "
        f"Supported: {', '.join(_inst.BASELINE_MODELS)}."
    )


def build_params(cfg: m.FitConfig) -> str:
    """Return the full text of ``params.csv`` for *cfg*."""
    lines: list[str] = [_PARAMS_HEADER]

    def comment(text: str) -> None:
        lines.append("#" + text)

    for comp in cfg.companions:
        comment(f"companion {comp.name} astrophysical params")
        lines.extend(_rr_rows(cfg, comp))
        lines.append(_param_row(f"{comp.name}_rsuma", comp.rsuma))
        lines.append(_param_row(f"{comp.name}_cosi", comp.cosi))
        lines.append(_param_row(f"{comp.name}_epoch", comp.epoch))
        lines.append(_param_row(f"{comp.name}_period", comp.period))
        lines.append(_param_row(f"{comp.name}_f_c", comp.f_c))
        lines.append(_param_row(f"{comp.name}_f_s", comp.f_s))

    comment("limb darkening coefficients per bandpass")
    for band in cfg.unique_bands():
        ldc = cfg.ldc.get(band) or m.default_ldc(band)
        lines.append(_param_row(f"host_ldc_q1_{band}", ldc.q1))
        lines.append(_param_row(f"host_ldc_q2_{band}", ldc.q2))

    comment("dilution per instrument")
    for inst in cfg.instruments:
        if inst.dilution is not None:
            lines.append(_param_row(f"dil_{inst.label}", inst.dilution))

    comment("white-noise floor (ln_err) per instrument")
    for inst in cfg.instruments:
        if inst.error == "sample":
            ln_err = inst.ln_err or m.default_ln_err()
            lines.append(_param_row(f"ln_err_flux_{inst.label}", ln_err))

    comment("baseline parameters per instrument")
    for inst in cfg.instruments:
        lines.extend(_baseline_param_rows(cfg, inst))

    return "\n".join(lines) + "\n"


# --- meta.yaml -------------------------------------------------------------
def build_meta(cfg: m.FitConfig) -> dict:
    """Machine-readable run identity (never parse the dir name for this)."""
    return {
        "target": cfg.target,
        "created_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "companions": [c.name for c in cfg.companions],
        "instruments": [
            {"label": i.label, "band": i.band, "data_file": i.data_file, "baseline": i.baseline}
            for i in cfg.instruments
        ],
        "bands": cfg.unique_bands(),
        "share_groups": [list(g) for g in cfg.share_groups],
        "chromatic": cfg.chromatic,
    }


# --- top-level -------------------------------------------------------------
def _validate(cfg: m.FitConfig) -> None:
    if not cfg.instruments:
        raise ValueError("FitConfig has no instruments")
    if not cfg.companions:
        raise ValueError("FitConfig has no companions")
    labels = [i.label for i in cfg.instruments]
    if len(set(labels)) != len(labels):
        raise ValueError(f"duplicate instrument labels: {labels}")
    known = set(labels)
    for group in cfg.share_groups:
        for member in group:
            if member not in known:
                raise ValueError(
                    f"baseline_share_flux member '{member}' is not among instruments {labels}"
                )


def write_config(cfg: m.FitConfig, run_dir: str | Path, *, write_run_py: bool = True) -> dict:
    """Write ``settings.csv``, ``params.csv``, ``meta.yaml`` (and ``run.py``).

    Returns a dict of the written paths. Data staging (the ``<inst>.csv`` files)
    is handled separately by :mod:`allesfitter.webgui.staging`.
    """
    _validate(cfg)
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    settings_path = run_dir / "settings.csv"
    params_path = run_dir / "params.csv"
    meta_path = run_dir / "meta.yaml"
    settings_path.write_text(build_settings(cfg))
    params_path.write_text(build_params(cfg))
    meta_path.write_text(yaml.safe_dump(build_meta(cfg), sort_keys=False))

    paths = {"settings": settings_path, "params": params_path, "meta": meta_path}
    if write_run_py:
        run_py_path = run_dir / "run.py"
        run_py_path.write_text(RUN_PY_TEMPLATE)
        paths["run_py"] = run_py_path
    return paths
